### PR TITLE
Consolidate Tracker Core module into Java Tracker

### PR DESCRIPTION
**Pull request by dstendardi**
As said in issue #115 I have refactored the project structure : 
 * The project is no more splitted in submodule (I removed the core module).
 * One Tracker test was not portable (timezone).
 * Tests have been switched from junit 3 to junit 4. 

For this commit I have keep the namespace `com.snowplowanalytics.snowplow.tracker.core`.
If your Ok I will remove this namespace in another pull request.

I also wonder why there is a war packaging (I'm not familiar with android world)

ping @epantera @lixiaoyi

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @dstendardi - this all looks good. Please go ahead and change the namespace to `com.snowplowanalytics.snowplow.tracker`, dropping the `core`.

And yep you can remove the war packaging (if it's needed for Android, it will live in snowplow-android-tracker)...

**Comment by alexanderdean** [comment]
Updated title

**Comment by alexanderdean** [comment]
Scheduling - this will be 0.7.0...

**Comment by dstendardi** [comment]
core package removed
war packaging removed

**Comment by alexanderdean** [comment]
Huge thanks @dstendardi - I am closing this now as this is fully merged into https://github.com/snowplow/snowplow-java-tracker/commits/release/0.7.0, which is the next release and will go out very shortly...

**Pull request closed without merging**
