### PR TITLE
Separated timestamp in 'true timestamp' and 'device created timestamp'

### PR DESCRIPTION
**Pull request by gaelrenoux**
Tests were OK before I modified them (because I kept the old version as deprecated), OK now with the new methods.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @gaelrenoux ! Can you sign out CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by gaelrenoux** [comment]
Already done.

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much

**Comment by gaelrenoux** [comment]
I realized today that I missed one point : in the BatchEmitter, I needed to update the payload_data schema. The 1-0-3 lacked the ttm attribute (see https://github.com/snowplow/iglu-central/commit/5a750c4d585f8708309d63830e1919accf420b14), I upgraded it to the 1-0-4.

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify. Thanks.

**Comment by gaelrenoux** [comment]
That's new.... Well, I signed it.

**Comment by snowplowcla** [comment]
Confirmed! @gaelrenoux has signed the Individual Contributor License Agreement. Thanks so much.

**Pull request merged**
