### PR TITLE
Add sample project & fix readme links

### PR DESCRIPTION
**Pull request by ninjabear**
This pull request is to add a sample project to the repository - this explains in code how to set-up and use the Java tracker. This project sends PageView events to a collector URI given as a command line argument. 

I've also fixed the readme in a separate commit.

### CODE REVIEW

**Comment by ninjabear** [comment]
Additional info: the build is broken for Java7 only, which is well over EOL

**Comment by alexanderdean** [comment]
> I'm of a mind to create a develop branch and merge it, wdyt?

Sure thing, go for it!

**Comment by BenFradet** [comment]
@alexanderdean could I get the appropriate perms to make `develop` the default branch?

**Comment by alexanderdean** [comment]
Done

**Pull request merged**
