### PR TITLE
Clean emitter

### PR DESCRIPTION
**Pull request by dstendardi**
Hello @alexanderdean,
This is a work in progress on the java tracker we have started a few monthes ago. I would be happy to get some review from your team. A quick summary of the changes we introduces : 

* batch emitter use post by default
* batch emitter has more thread safety (there was a bug in batch emitter, causing the queue to fill up)
* we introduced an adapter for http client, and an implementation for OkHttp (optional)
* we relay on guava for base 64 encoding
* a close method was added to the emitter, so licecycle managment app can purge the queue before stopping

I think I still need to update the documentation on how to instanciate the tracker before this PR can be merged.

cc @cmurer

### CODE REVIEW

**Comment by alexanderdean** [comment]
This is fantastic! Thanks so much @dstendardi. Scheduling for 0.8.0...

**Comment by dstendardi** [comment]
Still need to make it work on Java6/8  :p

2015-06-09 14:59 GMT-07:00 Alexander Dean <notifications@github.com>:

> This is fantastic! Thanks so much @dstendardi
> <https://github.com/dstendardi>. Scheduling for 0.8.0...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-java-tracker/pull/143#issuecomment-110517063>
> .
>



-- 
David Stendardi

**Comment by dstendardi** [comment]
Hi there ! I am closing this pr and resubmit it with all the fix needed (sorry for the noise)

**Comment by alexanderdean** [comment]
Ace - thanks @dstendardi !

**Comment by alexanderdean** [comment]
Hi @dstendardi, @epantera - we are hoping to work on this very soon. Would you be able to open a fresh PR?

**Comment by epantera** [comment]
Hey @dstendardi could you please make it fresh ?
thx

**Comment by dstendardi** [comment]
@epantera Sure. I will try to make it for the next week.

2015-08-27 11:25 GMT-07:00 Eric Pantera <notifications@github.com>:

> Hey @dstendardi <https://github.com/dstendardi> could you please make it
> fresh ?
> thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-java-tracker/pull/143#issuecomment-135514283>
> .
>



-- 
David Stendardi

**Comment by dstendardi** [comment]
Ok @alexanderdean. in order to make this PR works both on java6 and 7, i need to split out the OkHttpAdapter to another module. Are you ok with this ?

**Comment by dstendardi** [comment]
One last question ;-)
Are you ok to drop support for java 6 (which has been deprecated). It would simplify a lot the build process

**Comment by alexanderdean** [comment]
That's fine for the PR - we can always add it back in if users demand it! Thanks @dstendardi

**Pull request closed without merging**
