### PR TITLE
Fix Issue with OkHttpClientAdapter (closes #366)

### LINKED ISSUE #366: OkHttpClient return code is always = -1 when the response is code 404 or any other not successful code
**Describe the bug**
When OkHttpClient sends snowplow payload and it fails with any code like 404, then the return code is always = -1.  
It only sets to actual value, when the response is successful.

**To Reproduce**
OkHttpClientAdapter:

```
public int doPost(String url, String payload) {
        int returnValue = -1;

        RequestBody body = RequestBody.create(payload, JSON);
        Request request = new Request.Builder()
                .url(url)
                .addHeader("Content-Type", Constants.POST_CONTENT_TYPE)
                .post(body)
                .build();
        try (Response response = httpClient.newCall(request).execute()) {
            if (!response.isSuccessful()) {
                LOGGER.error("OkHttpClient POST Request failed: {}", response);
            } else {
                returnValue = response.code();
            }
        } catch (IOException e) {
            LOGGER.error("OkHttpClient POST Request failed: {}", e.getMessage());
        }

        return returnValue;
    }
```

**Expected behavior**
in the block

if (!response.isSuccessful()) {
}
there should be also returnValue = response.code(); So for example retry etc can pick up the code and evaluate the value.
better remove the else block like this:
```
                try (Response response = httpClient.newCall(request).execute()) {
			if (!response.isSuccessful()) {
				LOGGER.error("OkHttpClient POST Request failed: {}", response);
			}
			returnValue = response.code();
		} catch (IOException e) {
			LOGGER.error("OkHttpClient POST Request failed: {}", e.getMessage());
		}
```

Same applies for doGet() method
**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac Ventura 13.6 (22G120)
 - Version: Java 8

**Additional context**

### PR DESCRIPTION
**Pull request by eusorov**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by eusorov** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @eusorov has signed the Contributor License Agreement. Thanks so much.

**Review by matus-tomlein — APPROVED** [review]
Thanks a lot for the contribution @eusorov and for fixing the bug! This looks good to me!

**Pull request merged**
